/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nowe.presentacion;

import com.nowe.modelo.CDT;
import com.nowe.persistencia.AccesoCuentasBancarias;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Programacion
 */
public class GestionCDT extends javax.swing.JFrame {

    /**
     * Creates new form GestionCDT
     */
    public GestionCDT() {
        initComponents();
        groupAcciones.add(chkCrearCDT);
        groupAcciones.add(chkCerrarCDT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAcciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        chkCrearCDT = new javax.swing.JRadioButton();
        chkCerrarCDT = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCDT = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        mensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de CDT");

        chkCrearCDT.setText("Crear un CDT");
        chkCrearCDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCrearCDTActionPerformed(evt);
            }
        });

        chkCerrarCDT.setText("Cerrar un CDT");
        chkCerrarCDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCerrarCDTActionPerformed(evt);
            }
        });

        jLabel2.setText("Cuenta :");

        txtCuenta.setEnabled(false);

        jLabel3.setText("Interés :");

        txtInteres.setToolTipText("");
        txtInteres.setEnabled(false);

        jLabel4.setText("Monto :");

        txtMonto.setEnabled(false);

        jLabel5.setText("CDT :");

        txtCDT.setEnabled(false);

        btnAccion.setText("Realizar Acción");
        btnAccion.setToolTipText("");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        mensajeError.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCuenta)
                                            .addComponent(txtInteres)
                                            .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                                    .addComponent(chkCrearCDT))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chkCerrarCDT)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtCDT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(648, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(chkCrearCDT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(chkCerrarCDT)))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnAccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkCrearCDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCrearCDTActionPerformed
        // 1. Habilitar los controles de cuenta, intereses y monto
        txtCuenta.setEnabled(true);
        txtInteres.setEnabled(true);
        txtMonto.setEnabled(true);
        //2. Deshabilitar el control CDT y limpiarlo
        txtCDT.setText("");
        mensajeError.setText("");
        txtCDT.setEnabled(false);

    }//GEN-LAST:event_chkCrearCDTActionPerformed

    private void chkCerrarCDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCerrarCDTActionPerformed
        // 1. Habilitar el CDT
        txtCDT.setEnabled(true);
        // 2. Limpiar los otros controles y deshabilitarlos
        txtCuenta.setText("");
        txtInteres.setText("");
        txtMonto.setText("");
        mensajeError.setText("");
        txtCuenta.setEnabled(false);
        txtInteres.setEnabled(false);
        txtMonto.setEnabled(false);
    }//GEN-LAST:event_chkCerrarCDTActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        //1. Identificar si es la acción de crear un CDT
        //0. Definir variables
       mensajeError.setText("");
        AccesoCuentasBancarias acb1 = new AccesoCuentasBancarias();
        if (chkCrearCDT.isSelected()) {
            int cuenta;
            double interes, monto;
            CDT inversion;
            boolean exito;
            //1.1 Recoger los datos de los controles
            try {
                cuenta = Integer.parseInt(txtCuenta.getText());
                interes = Double.parseDouble(txtInteres.getText());
                monto = Double.parseDouble(txtMonto.getText());

                //1.2 Instanciar un objeto CDT
                inversion = new CDT(cuenta, interes, monto);

                //1.3 Llamar a creación del CDT
                exito = acb1.crearInversion(inversion);
                txtCuenta.setText("");
                txtInteres.setText("");
                txtMonto.setText("");
                if (exito) {
                    mensajeError.setText("Se ha realizado el alta de su CDT correctamente");
                } else {
                    mensajeError.setText("Se ha producido un error, no se realizó la acción correctamente");
                }

            } catch (ClassNotFoundException | SQLException ex) {
                mensajeError.setText("Se ha producido un error, no se realizó la acción correctamente");

            } catch (NumberFormatException ex) {
                mensajeError.setText("Los datos deben ser numéricos");
            }

        }

        //2. Identificar si es la acción de eliminar un CDT
        if (chkCerrarCDT.isSelected()) {
            //1. Declarar variables
            int CDT;
            boolean exito;
            try {
                //2. Recoger los datos de los controles
                CDT = Integer.parseInt(txtCDT.getText());
                //3 . Llamar al método correspondiente para cerrarla
                exito = acb1.cerrarInversion(CDT);
                txtCDT.setText("");
                if (exito) {
                    mensajeError.setText("Se ha realizado el cierre de su CDT correctamente");
                } else {
                    mensajeError.setText("Se ha producido un error, no se realizó la acción correctamente");
                }
                
            } catch (ClassNotFoundException | SQLException ex) {
                mensajeError.setText("Se ha producido un error en la BBDD, no se realizó la acción correctamente");
            } catch (NumberFormatException ex) {
                mensajeError.setText("Los datos deben ser numéricos");
            }
        }
    }//GEN-LAST:event_btnAccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JRadioButton chkCerrarCDT;
    private javax.swing.JRadioButton chkCrearCDT;
    private javax.swing.ButtonGroup groupAcciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JTextField txtCDT;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
