/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nowe.presentacion;

import com.nowe.persistencia.AccesoCuentasBancarias;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Programacion
 */
public class SolicitarSaldo extends javax.swing.JFrame {

    //Atributos
    private AccesoCuentasBancarias c1 = new AccesoCuentasBancarias();
    private int datoNumerico;

    /**
     * Creates new form SolicitarSaldo
     */
    public SolicitarSaldo() {
        initComponents();
        buttonGroup1.add(chkSCuenta);
        buttonGroup1.add(chkSCDT);
        buttonGroup1.add(chkSCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        chkSCuenta = new javax.swing.JRadioButton();
        chkSCDT = new javax.swing.JRadioButton();
        chkSCliente = new javax.swing.JRadioButton();
        lblConcepto = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnCSaldo = new javax.swing.JButton();
        txtSaldo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensajeError = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Diferentes tipos de consultas");

        chkSCuenta.setText("Saldo cuenta");
        chkSCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSCuentaActionPerformed(evt);
            }
        });

        chkSCDT.setText("Saldo CDT");
        chkSCDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSCDTActionPerformed(evt);
            }
        });

        chkSCliente.setText("Saldo Cliente");
        chkSCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSClienteActionPerformed(evt);
            }
        });

        txtDato.setEnabled(false);

        btnCSaldo.setText("Consultar Saldo");
        btnCSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSaldoActionPerformed(evt);
            }
        });

        txtSaldo.setEditable(false);

        taMensajeError.setEditable(false);
        taMensajeError.setColumns(20);
        taMensajeError.setRows(5);
        jScrollPane1.setViewportView(taMensajeError);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkSCDT)
                        .addGap(120, 120, 120)
                        .addComponent(lblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkSCuenta))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSaldo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(chkSCuenta)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chkSCDT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(chkSCliente)
                .addGap(32, 32, 32)
                .addComponent(btnCSaldo)
                .addGap(30, 30, 30)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSCuentaActionPerformed
        // TODO add your handling code here:
        if (chkSCuenta.isSelected()) {
            lblConcepto.setText("Cuenta :");
            txtDato.setText("");
            taMensajeError.setText("");
            txtSaldo.setText("");
            txtDato.setEnabled(true);
        } else {
            System.out.println("Se ha Des-seleccionado la opción de saldo de cuenta");
        }

    }//GEN-LAST:event_chkSCuentaActionPerformed

    private void chkSCDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSCDTActionPerformed
        // TODO add your handling code here:
        if (chkSCDT.isSelected()) {
            lblConcepto.setText("CDT :");
            txtDato.setText("");
             taMensajeError.setText("");
              txtSaldo.setText("");
               txtDato.setEnabled(true);
        } else {
            System.out.println("Se ha des -seleccionado la opción de saldo CDT");
        }

    }//GEN-LAST:event_chkSCDTActionPerformed

    private void chkSClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSClienteActionPerformed
        // TODO add your handling code here:
        if (chkSCliente.isSelected()) {
            lblConcepto.setText("NIF :");
            txtDato.setText("");
             taMensajeError.setText("");
              txtSaldo.setText("");
              txtDato.setEnabled(true);
        } else {
            System.out.println("Se ha des - seleccionado la opción de saldo del cliente ");
        }

    }//GEN-LAST:event_chkSClienteActionPerformed
    private void VerificarNumero() {
        //1. Recoger el dato de la caja de texto
        String datoTexto = txtDato.getText();

        //2. Si se puede convertir a entero
        try {
            datoNumerico = Integer.parseInt(datoTexto);
        } catch (Exception ex) {
            taMensajeError.setText("El dato tiene que ser numérico");
            taMensajeError.setText(ex.toString());
        }
    }
    
    private void VerificaVacio(){
        //1. Recoger el dato de la caja de texto
        String datoTexto = txtDato.getText();
        if (datoTexto.equals("")) {
            taMensajeError.setText("El dato tiene que ser numérico ");
        }
    }
    private void btnCSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSaldoActionPerformed
        //Dependiendo del radio boton seleccionado es el saldo que consultará
        if (chkSCuenta.isSelected()) {
            VerificarNumero();
            VerificaVacio();
            
            try {
                txtSaldo.setText(Double.toString(c1.consultaSaldo(datoNumerico)));
            } catch (ClassNotFoundException | SQLException ex) {
                taMensajeError.setText(ex.toString());
            }
        }

        //En caso de que se seleccione el boton CDT
        if (chkSCDT.isSelected()) {
            //1. Recoger los datos de los controles
           VerificarNumero();
           VerificaVacio();
           
            // 2. Convertir (si es necesario)
            try {
                //3 . Rellenar el fieldText del Saldo con el método correspondiente
                txtSaldo.setText(Double.toString(c1.consultaSaldoCDT(datoNumerico)));
            } catch (ClassNotFoundException | SQLException ex) {
                taMensajeError.setText(ex.toString());
            }
        }

        //En caso de que se seleccione el boton de Saldo Cliente
        if (chkSCliente.isSelected()) {
            //1. Recoger el valor de la caja de texto
            
            String numNIf = txtDato.getText();
            try {
                //2. Llamar al método de saldo de cliente
                txtSaldo.setText(Double.toString(c1.consultaSaldoTotal(numNIf)));
            } catch (ClassNotFoundException | SQLException ex) {
                taMensajeError.setText(ex.toString());
            }
        }
    }//GEN-LAST:event_btnCSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitarSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSaldo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chkSCDT;
    private javax.swing.JRadioButton chkSCliente;
    private javax.swing.JRadioButton chkSCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JTextArea taMensajeError;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
